name: Daily Fetch Hedge Fund Allocations

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      run: python fetch_hedge_fund_allocations.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update of hedge fund allocations"
        branch: main
